# https://pyuvsim.readthedocs.io/en/latest/parameter_files.html
filing:
  outdir: '.'
  outfile_name: 'test'
  output_format: 'uvh5'
freq:
  Nfreqs: 1
  channel_width: 80000.0
  start_freq: 100000000.0
sources:
  catalog: 'sources.txt'
  table_name: single  # Required for non-GLEAM VO table files
  id_column: SOURCE_ID  # Required for non-GLEAM VO table files
  flux_columns: Flux  # Required for non-GLEAM VO table files
  ra_column: RA_J2000  # Recommended for non-GLEAM VO table files
  dec_column: Dec_J2000  # Recommended for non-GLEAM VO table files
telescope:
  array_layout: 'antennas.txt'
  telescope_config_name: 'telescope.yaml'
time:
  Ntimes: 1
  integration_time: 40
  start_time: 2458902.4
